# Copyright 2026 Spectrayan — Apache 2.0
"""
High-level memory client wrapping MCP memory tools.

Provides a Pythonic API over the 15 memory tools exposed by the
Spector MCP server. Each method maps to a single ``tools/call`` invocation.
"""

from __future__ import annotations

from typing import Optional, TYPE_CHECKING

from spector.models import (
    CognitiveRecord,
    CognitiveResult,
    MemoryInsight,
    MemorySource,
    MemoryStatus,
    MemoryType,
    RecallOptions,
)

if TYPE_CHECKING:
    from spector.transport import StdioTransport


class MemoryClient:
    """Cognitive memory operations — wraps all ``memory_*`` MCP tools.

    Do not instantiate directly. Access via ``SpectorClient.memory``::

        with SpectorClient(jar_path="spector.jar") as client:
            client.memory.remember("User prefers dark mode")
            results = client.memory.recall("preferences")
    """

    def __init__(self, transport: StdioTransport):
        self._transport = transport

    # ── Ingestion ──

    def remember(
        self,
        text: str,
        *,
        type: MemoryType = MemoryType.SEMANTIC,
        source: MemorySource = MemorySource.OBSERVED,
        tags: Optional[list[str]] = None,
        id: Optional[str] = None,
        interest: float = 0.0,
        challenge: float = 0.0,
        urgency: float = 0.0,
        valence: int = 0,
        arousal: int = 0,
    ) -> str:
        """Stores a cognitive memory.

        If ``id`` is not provided, a TSID is auto-generated by the server.

        Args:
            text: The memory content to store.
            type: Cognitive tier (default: SEMANTIC).
            source: Provenance (default: OBSERVED).
            tags: Optional list of synaptic tag strings.
            id: Optional explicit ID. If omitted, auto-generated.
            interest: ICNU interest score (0.0-1.0).
            challenge: ICNU challenge score (0.0-1.0).
            urgency: ICNU urgency score (0.0-1.0).
            valence: Emotional coloring (-128 to +127).
            arousal: Emotional intensity (0-255).

        Returns:
            The memory ID (auto-generated or explicit).
        """
        args: dict = {
            "text": text,
            "tier": type.value,
            "source": source.value,
        }
        if id:
            args["id"] = id
        if tags:
            args["tags"] = ",".join(tags)
        if interest > 0:
            args["interest"] = interest
        if challenge > 0:
            args["challenge"] = challenge
        if urgency > 0:
            args["urgency"] = urgency
        if valence != 0:
            args["valence"] = valence
        if arousal != 0:
            args["arousal"] = arousal

        result = self._transport.call_tool("memory_remember", args)

        # Extract the ID from the response text (e.g., "✅ Stored SEMANTIC memory 'ABC123'")
        if "'" in result:
            parts = result.split("'")
            if len(parts) >= 2:
                return parts[1]
        return id or result

    # ── Recall ──

    def recall(
        self,
        query: str,
        *,
        top_k: int = 10,
        tags: Optional[list[str]] = None,
        min_importance: float = 0.0,
        options: Optional[RecallOptions] = None,
    ) -> str:
        """Recalls memories matching a query with cognitive scoring.

        Args:
            query: The query text.
            top_k: Maximum results (default: 10).
            tags: Optional synaptic tag filter.
            min_importance: Minimum importance threshold.
            options: Full RecallOptions (overrides individual params).

        Returns:
            The raw recall result text from the MCP tool.
        """
        if options:
            args = {"query": query, **options.to_args()}
        else:
            args: dict = {"query": query, "top_k": top_k}
            if tags:
                args["tags"] = ",".join(tags)
            if min_importance > 0:
                args["min_importance"] = min_importance

        return self._transport.call_tool("memory_recall", args)

    # ── Inspect / Browse / Export ──

    def inspect(self, id: str) -> str:
        """Returns the full cognitive X-ray for a memory.

        Args:
            id: The memory ID to inspect.

        Returns:
            The raw inspect result text (includes header, flags, vector info).
        """
        return self._transport.call_tool("memory_inspect", {"id": id})

    def browse(self, *tags: str) -> str:
        """Browses memories by tag (AND semantics, no vector search).

        Args:
            *tags: One or more tag strings to filter by.

        Returns:
            The raw browse result text listing matching memories.
        """
        return self._transport.call_tool("memory_browse", {
            "tags": ",".join(tags),
        })

    def export_json(self) -> str:
        """Exports all memories as a JSON array.

        Returns:
            JSON string containing all live memory records.
        """
        return self._transport.call_tool("memory_export", {})

    # ── Lifecycle ──

    def forget(self, id: str) -> str:
        """Tombstones a memory by ID (permanent deletion from recall).

        Args:
            id: The memory ID to forget.

        Returns:
            Confirmation text.
        """
        return self._transport.call_tool("memory_forget", {"id": id})

    def reinforce(self, id: str, valence: int = 1) -> str:
        """Reports positive/negative outcome for a memory (LTP reinforcement).

        Args:
            id: The memory ID to reinforce.
            valence: Positive (1) or negative (-1) feedback.

        Returns:
            Confirmation text.
        """
        return self._transport.call_tool("memory_reinforce", {
            "id": id,
            "valence": valence,
        })

    def suppress(self, id: str, reason: str = "") -> str:
        """Suppresses a memory from recall results (reversible).

        Args:
            id: The memory ID to suppress.
            reason: Optional reason for suppression.

        Returns:
            Confirmation text.
        """
        args = {"id": id}
        if reason:
            args["reason"] = reason
        return self._transport.call_tool("memory_suppress", args)

    def resolve(self, id: str) -> str:
        """Marks a memory as resolved (Zeigarnik Effect — task completed).

        Args:
            id: The memory ID to resolve.

        Returns:
            Confirmation text.
        """
        return self._transport.call_tool("memory_resolve", {"id": id})

    # ── Analysis ──

    def introspect(self, topic: str) -> str:
        """Metamemory self-analysis on a topic.

        Args:
            topic: The topic to analyze.

        Returns:
            The raw introspection result text.
        """
        return self._transport.call_tool("memory_introspect", {"topic": topic})

    def why_not(self, id: str, query: str) -> str:
        """Explains why a specific memory was not recalled for a query.

        Args:
            id: The memory ID that was expected.
            query: The query it should have matched.

        Returns:
            Diagnostic explanation text.
        """
        return self._transport.call_tool("memory_why_not", {
            "memory_id": id,
            "query": query,
        })

    def compute_importance(self, text: str) -> str:
        """Estimates the importance score for a text (read-only, no ingestion).

        Args:
            text: The text to evaluate.

        Returns:
            Importance estimation text.
        """
        return self._transport.call_tool("memory_compute_importance", {"text": text})

    # ── Status ──

    def status(self) -> str:
        """Returns memory tier counts and persistence info.

        Returns:
            The raw status text.
        """
        return self._transport.call_tool("memory_status", {})

    def scratchpad(self, text: str) -> str:
        """Stores ephemeral text in working memory.

        Args:
            text: The scratchpad content.

        Returns:
            Confirmation text.
        """
        return self._transport.call_tool("memory_scratchpad", {"text": text})

    def reminder(self, text: str, delay_seconds: int = 0) -> str:
        """Schedules a time-triggered reminder.

        Args:
            text: The reminder content.
            delay_seconds: Seconds from now (0 = immediate trigger).

        Returns:
            Confirmation text.
        """
        args: dict = {"text": text}
        if delay_seconds > 0:
            args["delay_seconds"] = delay_seconds
        return self._transport.call_tool("memory_reminder", args)
