/*
 * Copyright 2026 Spectrayan
 *
 * Licensed under the Business Source License 1.1 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://github.com/spectrayan/spector/blob/main/spector-memory/LICENSE
 *
 * Change Date: May 27, 2030
 * Change License: Apache License, Version 2.0
 */
package com.spectrayan.spector.memory.model;

import com.spectrayan.spector.memory.pathway.*;

import com.spectrayan.spector.memory.reflect.*;

import com.spectrayan.spector.memory.persist.*;

import com.spectrayan.spector.memory.bootstrap.*;

import com.spectrayan.spector.memory.api.*;

import com.spectrayan.spector.memory.graph.GraphHealthMetrics;

import java.time.Duration;

/**
 * Report generated by the reflection (sleep consolidation) process.
 *
 * @param consolidatedCount      number of episodic clusters promoted to Semantic tier
 * @param tombstonedCount        number of memories tombstoned during Deep Sleep pruning
 * @param compactedPartitions    number of partitions that were rebuilt after tombstone threshold
 * @param temporalPrunedCount    number of temporal chain nodes pruned (older than retention period)
 * @param duration               total time taken for the reflection cycle
 * @param graphHealth            optional graph health metrics snapshot (may be {@code null})
 * @param soulDriftedCount       count of memories detected with outdated soul version
 * @param soulRefusedCount       count of soul-drifted memories re-fused with updated importance
 * @param averageImportanceDelta average absolute delta in importance following soul re-fusion
 * @param logTurnsConsolidated   count of episodic log conversation turns processed
 */
public record ReflectReport(
        int consolidatedCount,
        int tombstonedCount,
        int compactedPartitions,
        int temporalPrunedCount,
        Duration duration,
        GraphHealthMetrics graphHealth,
        int soulDriftedCount,
        int soulRefusedCount,
        float averageImportanceDelta,
        int logTurnsConsolidated
) {

    /**
     * Backward-compatible 6-argument constructor with graph health metrics.
     */
    public ReflectReport(int consolidatedCount, int tombstonedCount,
                         int compactedPartitions, int temporalPrunedCount,
                         Duration duration, GraphHealthMetrics graphHealth) {
        this(consolidatedCount, tombstonedCount, compactedPartitions,
                temporalPrunedCount, duration, graphHealth, 0, 0, 0.0f, 0);
    }

    /**
     * Backward-compatible 5-argument constructor without graph health metrics.
     */
    public ReflectReport(int consolidatedCount, int tombstonedCount,
                         int compactedPartitions, int temporalPrunedCount,
                         Duration duration) {
        this(consolidatedCount, tombstonedCount, compactedPartitions,
                temporalPrunedCount, duration, null, 0, 0, 0.0f, 0);
    }

    /**
     * Returns true if any work was done during this reflection cycle.
     */
    public boolean hadActivity() {
        return consolidatedCount > 0 || tombstonedCount > 0
                || compactedPartitions > 0 || temporalPrunedCount > 0
                || soulDriftedCount > 0 || soulRefusedCount > 0
                || logTurnsConsolidated > 0
                || (graphHealth != null && graphHealth.totalEdgesDecayed() > 0);
    }

    /**
     * Empty report — no work done.
     */
    public static final ReflectReport EMPTY = new ReflectReport(0, 0, 0, 0, Duration.ZERO, null, 0, 0, 0.0f, 0);
}
