/*
 * Copyright 2026 Spectrayan
 *
 * Licensed under the Business Source License 1.1 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://github.com/spectrayan/spector/blob/main/spector-memory/LICENSE
 *
 * Change Date: May 27, 2030
 * Change License: Apache License, Version 2.0
 */
package com.spectrayan.spector.memory.aisme.pcmn;

import com.spectrayan.spector.commons.error.ErrorCode;
import com.spectrayan.spector.commons.error.SpectorValidationException;

import java.util.Arrays;

/**
 * Immutable record representing a top-down prediction for a specific cortical memory tier.
 *
 * <h3>Biological Analog: Descending Corticocortical Prediction Signal</h3>
 * <p>Carries the expected neural representation generated by higher-order cognitive tiers
 * to gate and constrain sensory and lower-tier memory retrieval.</p>
 */
public record TierPrediction(
        int tierLevel,
        float[] predictionVector,
        float[] precisionWeights,
        long timestampMs
) {

    /**
     * Compact constructor with validation and defensive copies.
     */
    public TierPrediction {
        if (predictionVector == null || precisionWeights == null) {
            throw new SpectorValidationException(ErrorCode.ARGUMENT_INVALID, "Vectors must not be null");
        }
        if (predictionVector.length != precisionWeights.length) {
            throw new SpectorValidationException(ErrorCode.ARGUMENT_INVALID, "Prediction and precision vector dimensions must match");
        }
        if (predictionVector.length == 0) {
            throw new SpectorValidationException(ErrorCode.ARGUMENT_INVALID, "Dimension must be positive");
        }

        predictionVector = Arrays.copyOf(predictionVector, predictionVector.length);
        precisionWeights = Arrays.copyOf(precisionWeights, precisionWeights.length);
    }

    public int dimensions() {
        return predictionVector.length;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TierPrediction that)) return false;
        return tierLevel == that.tierLevel &&
                timestampMs == that.timestampMs &&
                Arrays.equals(predictionVector, that.predictionVector) &&
                Arrays.equals(precisionWeights, that.precisionWeights);
    }

    @Override
    public int hashCode() {
        int result = tierLevel;
        result = 31 * result + Arrays.hashCode(predictionVector);
        result = 31 * result + Arrays.hashCode(precisionWeights);
        result = 31 * result + Long.hashCode(timestampMs);
        return result;
    }

    @Override
    public String toString() {
        return "TierPrediction{" +
                "tier=" + tierLevel +
                ", dim=" + predictionVector.length +
                ", timestampMs=" + timestampMs +
                '}';
    }
}
