/*
 * Copyright 2026 Spectrayan
 *
 * Licensed under the Business Source License 1.1 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://github.com/spectrayan/spector/blob/main/spector-synapse/LICENSE
 *
 * Change Date: July 6, 2030
 * Change License: Apache License, Version 2.0
 */
package com.spectrayan.spector.synapse.openapi;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.context.WebApplicationContext;

/**
 * Validates and exports the canonical OpenAPI 3.1 specification for Spector Synapse.
 *
 * <p>During CI or local test execution, this test retrieves the live OpenAPI 3.1 specification
 * generated by SpringDoc OpenAPI and writes it to {@code docs/openapi.yaml}, ensuring
 * that the specification remains committed, versioned, and always in sync with code changes.</p>
 */
@SpringBootTest
@ActiveProfiles("test")
@WithMockUser
@DisplayName("OpenAPI 3.1 Specification Export Test")
class OpenApiSpecExportTest {

    @Autowired
    private WebApplicationContext wac;

    @Test
    @DisplayName("Verify /v3/api-docs.yaml returns valid OpenAPI spec and export to docs/openapi.yaml")
    void exportOpenApiYaml() throws Exception {
        MockMvc mockMvc = MockMvcBuilders.webAppContextSetup(wac).build();

        MvcResult result = mockMvc.perform(get("/v3/api-docs.yaml"))
                .andExpect(status().isOk())
                .andReturn();

        String yaml = result.getResponse().getContentAsString(StandardCharsets.UTF_8);

        assertThat(yaml).isNotBlank();
        assertThat(yaml).contains("openapi: 3.1.");
        assertThat(yaml).contains("title: Spector Cognitive Memory & Search API");
        assertThat(yaml).contains("/api/v1/memory/remember");
        assertThat(yaml).contains("operationId: rememberMemory");

        // Write canonical spec to docs/openapi.yaml
        Path outputPath = Paths.get("../../docs/openapi.yaml").toAbsolutePath().normalize();
        Files.createDirectories(outputPath.getParent());
        Files.writeString(outputPath, yaml, StandardCharsets.UTF_8);

        assertThat(Files.exists(outputPath)).isTrue();
        assertThat(Files.size(outputPath)).isGreaterThan(1000L);
    }
}
