#!/usr/bin/env python3
# Copyright 2026 Spectrayan
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
MindSpan v2: Full Gemini-3.1-Flash-Lite Longitudinal Dataset Synthesizer.

Every single conversation turn is generated by Gemini  zero template concatenation.

Architecture:
  - Life Arc Engine: 12 quarterly narrative contexts (2024-2026)
  - Surprise Event Pool: 100+ unique daily micro-events
  - Rolling 3-Day Continuity Buffer: cross-day contextual references
  - Variable Session/Turn Counts: 1-6 sessions, 2-8 turns per session
  - Biographical Epoch: 7 life phases  500 memories (3,500+ records)
  - Checkpoint/Resume: resilient batch processing with weekly batches
"""

import os
import sys
import json
import time
import random
import ssl
import urllib.request
import datetime
import traceback
from pathlib import Path

random.seed(None)  # True randomness, not fixed seed

DATASET_DIR = Path(os.environ.get("MINDSPAN_DATA_DIR", Path(__file__).resolve().parent.parent / "data"))
DAILY_DIR = DATASET_DIR / "daily"
DAILY_DIR.mkdir(parents=True, exist_ok=True)
CHECKPOINT_FILE = DATASET_DIR / "synthesis_checkpoint.json"
CONTINUITY_FILE = DATASET_DIR / "continuity_buffer.json"

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")

MODEL = "gemini-3.1-flash-lite"
SSL_CTX = ssl._create_unverified_context()
TEMPERATURE = 0.85
BATCH_SIZE = 7  # Weekly batches

if not GEMINI_API_KEY:
    print("ERROR: GEMINI_API_KEY not found. Set env var GEMINI_API_KEY")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Gemini API Caller
# ---------------------------------------------------------------------------
def call_gemini(prompt, max_retries=6, temperature=TEMPERATURE):
    """Call Gemini-3.1-Flash-Lite and return parsed JSON response."""
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{MODEL}:generateContent?key={GEMINI_API_KEY}"

    payload = json.dumps({
        "contents": [{"role": "user", "parts": [{"text": prompt}]}],
        "generationConfig": {
            "temperature": temperature,
            "maxOutputTokens": 8192,
            "responseMimeType": "application/json"
        }
    }).encode("utf-8")

    for attempt in range(max_retries):
        req = urllib.request.Request(url, data=payload, headers={"Content-Type": "application/json"})
        try:
            with urllib.request.urlopen(req, context=SSL_CTX, timeout=60) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                candidates = data.get("candidates", [])
                if candidates and "content" in candidates[0]:
                    txt = candidates[0]["content"]["parts"][0]["text"]
                    return json.loads(txt)
                else:
                    reason = candidates[0].get("finishReason", "UNKNOWN") if candidates else "NO_CANDIDATES"
                    print(f"  Empty response (attempt {attempt+1}): {reason}")
        except json.JSONDecodeError as e:
            print(f"  JSON parse error (attempt {attempt+1}): {e}")
            time.sleep(1)
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", errors="ignore")[:300]
            if e.code == 429:
                wait = (attempt + 1) * 5
                print(f"  Rate limited (429), backing off {wait}s...")
                time.sleep(wait)
            elif e.code == 503:
                wait = (attempt + 1) * 3
                print(f"  Server overloaded (503), retrying in {wait}s...")
                time.sleep(wait)
            else:
                print(f"  HTTP {e.code}: {body}")
                time.sleep(2)
        except Exception as e:
            print(f"  API error (attempt {attempt+1}): {e}")
            time.sleep(2)

    print(f"  FAILED after {max_retries} retries. Returning empty list.")
    return []

# ---------------------------------------------------------------------------
# Entity Detection
# ---------------------------------------------------------------------------
ENTITIES = {
    "Mike": "PERSON", "Sarah": "PERSON", "Ethan": "PERSON", "Lily": "PERSON",
    "Cooper": "ANIMAL", "Jarvis": "SOFTWARE",
    "Tom": "PERSON", "Linda": "PERSON", "Robert": "PERSON", "Patricia": "PERSON",
    "Emily": "PERSON", "Mark": "PERSON", "Maya": "PERSON", "Daniel": "PERSON",
    "Arthur": "PERSON", "Greg": "PERSON", "Anika": "PERSON", "Dave": "PERSON",
    "Vertex Health": "ORG", "CareConnect": "SOFTWARE", "Frisco FC": "ORG",
    "Lie-Nielsen": "ORG", "Little Sprouts": "ORG", "UIUC": "ORG",
    "Cottonwood Creek": "LOCATION", "Naperville": "LOCATION", "Frisco": "LOCATION",
    "Plano": "LOCATION", "Austin": "LOCATION", "Denver": "LOCATION",
    "Seattle": "LOCATION", "Chicago": "LOCATION", "Lake Geneva": "LOCATION",
    "Warren Sports Complex": "LOCATION", "Bourgeois Pig": "LOCATION",
}

def detect_entities(text):
    return [{"name": n, "type": t} for n, t in ENTITIES.items() if n in text]

def to_epoch_ms(dt):
    return int(dt.replace(tzinfo=datetime.timezone.utc).timestamp() * 1000)

# ---------------------------------------------------------------------------
# Checkpoint Manager
# ---------------------------------------------------------------------------
def load_checkpoint():
    if CHECKPOINT_FILE.exists():
        return json.loads(CHECKPOINT_FILE.read_text(encoding="utf-8"))
    return {"bio_phases_done": [], "daily_days_done": [], "queries_done": False}

def save_checkpoint(cp):
    CHECKPOINT_FILE.write_text(json.dumps(cp, indent=2), encoding="utf-8")

def load_continuity():
    if CONTINUITY_FILE.exists():
        return json.loads(CONTINUITY_FILE.read_text(encoding="utf-8"))
    return {"recent_days": []}

def save_continuity(buf):
    CONTINUITY_FILE.write_text(json.dumps(buf, indent=2), encoding="utf-8")

# ===================================================================
# PART 1: BIOGRAPHICAL EPOCH (7 life phases  500 memories)
# ===================================================================

LIFE_PHASES = [
    {
        "id": "early_childhood",
        "label": "Early Childhood (1990-1998)",
        "years": (1990, 1998),
        "prompt_context": """
Mike Thompson's early childhood in Naperville, Illinois (1990-1998, ages 0-8).
Family: Father Tom Thompson (high school history teacher), Mother Linda Thompson (part-time
librarian at Nichols Library), younger sister Emily Thompson (born 1993).
Setting: A classic 1990s Midwestern suburban childhood  riding bikes on Washington Street,
catching fireflies in the backyard, Saturday morning cartoons (Rugrats, Doug), family trips
to Brookfield Zoo, Tom reading aloud from "Treasure Island" and "The Hobbit", Linda teaching
Mike to bake chocolate chip cookies, building snow forts in Illinois winters, Thanksgiving
at Great-Grandpa Arthur Thompson's house (Arthur is a WWII veteran who tells war stories and
has a 1944 Elgin pocket watch), summer trips to Indiana Dunes, learning to swim at Centennial
Beach, Mike's first computer (a beige Compaq Presario), family dinners at Lou Malnati's,
trick-or-treating on Halloween in leaf-covered Naperville neighborhoods, Mike breaking his
arm falling from the backyard oak tree (age 6), Emily's first steps, family road trip to
Wisconsin Dells.

These are fragmentary childhood memories  some vivid (birthday parties, injuries, holidays),
some hazy and sensory (the smell of Mom's kitchen, sound of Dad's car in the driveway,
texture of the living room carpet). Many are brief impressions, not full narratives.
""",
    },
    {
        "id": "late_childhood",
        "label": "Late Childhood & Elementary (1998-2004)",
        "years": (1998, 2004),
        "prompt_context": """
Mike Thompson's late childhood and middle school in Naperville, IL (1998-2004, ages 8-14).
School: Highlands Elementary then Kennedy Junior High. Close friend: Danny Kowalski (neighbor).
Activities: Travel soccer team (Naperville Strikers), Boy Scouts Troop 505 (earned Eagle Scout),
building model rockets, dad Tom teaching car maintenance on the family 1998 Subaru Outback,
learning to code HTML and making a terrible GeoCities website about soccer, playing Age of
Empires II and SimCity 2000, getting his first iPod (3rd gen), family annual trips to Art
Institute of Chicago with Mom, grandpa Arthur declining in health (early Parkinson's tremors),
sister Emily starting competitive gymnastics, Mike's first woodworking project (a crooked
birdhouse in Dad's garage using Tom's old hand saw), reading Harry Potter books, riding bikes
to DuPage River Trail, first cell phone (Nokia 3310), 9/11 and watching it on the school TV.

Mix of detailed memories and vague impressions. Some memories are about specific objects
(the iPod, the Nokia phone), some are sensory (smell of cut grass at soccer practice),
some are relational (arguments with Emily, Danny's sleepover birthday parties).
""",
    },
    {
        "id": "high_school",
        "label": "High School at Naperville Central (2004-2008)",
        "years": (2004, 2008),
        "prompt_context": """
Mike Thompson at Naperville Central High School (2004-2008, ages 14-18).
Varsity soccer team (midfielder, captain senior year). AP Computer Science teacher Mr. Hendricks
sparked his love for programming. First experiments with Ubuntu Linux on Dad's old Pentium 4.
Built a custom PC with Danny Kowalski. First girlfriend: Jessica Alvarez (junior year, dated
6 months). Part-time job bagging groceries at Jewel-Osco on Ogden Ave. SAT prep stress.
Arthur Thompson (great-grandfather) gifting the 1944 Elgin pocket watch at graduation dinner
(June 2008)  "Keep time well, Mike, it's the one thing you can never buy back."
Arthur's WWII stories becoming more precious as his health worsened (Parkinson's). Senior
prom at Naper Settlement. College application anxiety (accepted to UIUC, rejected from
Northwestern). Summer job lifeguarding at Centennial Beach. Learning to drive in Tom's Subaru.
Emily (age 11-15) becoming an annoying but beloved little sister. Mom Linda volunteering
at the school library. Family dinners getting rarer as Mike had more evening activities.
Discovering The Shins and Radiohead. First heartbreak when Jessica broke up before college.
""",
    },
    {
        "id": "college",
        "label": "College at UIUC (2008-2012)",
        "years": (2008, 2012),
        "prompt_context": """
Mike Thompson at University of Illinois Urbana-Champaign (2008-2012, ages 18-22).
Dorm: Townsend Hall freshman year, then off-campus apartment on Green Street with roommate
Dave Nguyen (future best man). Double major: Computer Science and Economics. Professors he
remembers: Dr. Patel (algorithms), Dr. Chen (microeconomics). Intramural soccer captain.
Late-night coding sessions at Grainger Library. Discovering craft coffee at Espresso Royale.
Summer internships: sophomore year at a logistics company in Oak Brook writing Python scripts,
junior year at a small HealthTech startup in River North (pivotal career moment). Weekend
road trips to Chicago with Dave. Learning to cook ramen and scrambled eggs in a tiny kitchen.
Arthur Thompson passing away in fall 2010  Mike wearing the Elgin watch to the funeral.
Emily starting undergrad at Northwestern (pre-med). Meeting Sarah Moretti at Bourgeois Pig
cafe in Lincoln Park on a rainy Friday afternoon in October 2011  she was sketching
typography for her design portfolio, they talked for three hours about architecture, Italian
food, and family road trips. First date at the Art Institute a week later. Graduation with
honors (May 2012), Dave Nguyen planning a ridiculous graduation road trip to Nashville.
""",
    },
    {
        "id": "young_adult",
        "label": "Young Adult, Love & Early Career (2012-2016)",
        "years": (2012, 2016),
        "prompt_context": """
Mike Thompson's early career and courtship with Sarah (2012-2016, ages 22-26).
Career: Junior PM at a HealthTech incubator in Chicago's River North, promoted to PM within
18 months. Learning the craft of product management  user interviews, sprint planning,
stakeholder politics. Boss: Marcus Chen, a demanding but brilliant VP who taught Mike to
"always bring data to a knife fight." First big win: reducing patient onboarding dropoff by
28% through telemetry pipeline work. First marathon along Chicago Lakefront Trail (2014,
3:48:32). Apartment in Lincoln Square with Sarah (moved in together 2013).
Courtship with Sarah Moretti: weekend brunch at Ann Sather, Sarah teaching Mike about
typography and color theory, Mike teaching Sarah about agile methodology, visiting Sarah's
parents Robert Miller and Patricia Moretti-Miller in Austin (Robert's woodworking shop
amazed Mike), Sarah's Italian grandmother Nonna Lucia's Sunday gravy recipe becoming Mike's
favorite comfort food, weekend trips to Door County and Galena, adopting succulents that
keep dying, proposal at Millennium Park under evening lights in December 2015 (Dave helped
plan it), engagement party at Robert's Austin backyard.
""",
    },
    {
        "id": "marriage_parenthood",
        "label": "Marriage & Early Parenthood (2016-2019)",
        "years": (2016, 2019),
        "prompt_context": """
Mike Thompson's marriage and early fatherhood (2016-2019, ages 26-29).
Wedding: September 17, 2016 at Riviera Ballroom overlooking Lake Geneva, Wisconsin. Dave
Nguyen as best man gave a hilarious toast about the Nashville road trip. Tom Thompson quoted
Marcus Aurelius. Sarah's dress was vintage lace from Patricia's collection. Honeymoon in
Amalfi Coast, Italy  visiting the Moretti family village near Positano.
Robert Miller gifting Lie-Nielsen hand planes in Austin (July 2017): No. 4 smoothing plane,
No. 7 jointer, bevel-edge bench chisels. Entire afternoon learning to tune the frog, hone
A2 tool steel to 8000 grit on Japanese waterstones. Robert's philosophy: "The tool should
feel like an extension of your hand."
Birth of Ethan Thompson: October 24, 2017 at 3:15 AM, Prentice Women's Hospital, Chicago.
7 lbs 8 oz. Sarah was incredible. Mike cried holding him for the first time. Sleep deprivation
becoming the new normal. Learning to change diapers at 3 AM. Sarah returning to freelance
design work from home. Mike getting promoted to Senior PM. Emily finishing medical school,
starting pediatric residency in Denver. Ethan's first steps (14 months). First family
Christmas with all the grandparents in Naperville. Building a wooden toy chest for Ethan
using Robert's tools.
""",
    },
    {
        "id": "maturity_transition",
        "label": "Maturity, Loss & Transition (2019-2023)",
        "years": (2019, 2023),
        "prompt_context": """
Mike Thompson's maturation and life transitions (2019-2023, ages 29-33).
2019-2020: Remote work transition during pandemic. Built a custom standing desk with motorized
legs and solid white oak top. Restored a 1950s Stanley No. 5 jack plane from Evanston estate
sale. Ethan (age 2-3) becoming a toddler tornado. Sarah launching DesignSystemsPro online
course. Tom Thompson developing osteoarthritis in right knee (2021), starting PT at
Northwestern in Chicago.
Robert Miller's illness: Robert diagnosed with pulmonary fibrosis (2021). Multiple trips
to Austin to visit. Robert's condition worsening through early 2022. Robert passing away
peacefully on March 10, 2022. Sarah finding Robert's handwritten woodworking master notes.
Mike promising to honor the craft legacy. Funeral in Austin, Patricia struggling with grief.
Relocation: Accepted Senior PM role at Vertex Health in Plano, TX. Moved family from Chicago
to Frisco, TX in June 2022. New house near Cottonwood Creek Trail. Setting up garage
woodworking workshop. Ethan starting kindergarten at Frisco Elementary. Sarah setting up
home studio.
Adopting Cooper: Golden Retriever puppy from McKinney rescue, December 2022. Ethan (age 5)
immediately inseparable from Cooper.
Birth of Lily Thompson: May 29, 2023 at Texas Health Presbyterian, Plano. Ethan brought
her a teddy bear. Patricia visiting from Austin for a month to help. The family feeling
complete. Daniel Miller (Sarah's brother, airline pilot) visiting from Seattle.
""",
    },
]

def generate_biographical_phase(phase, batch_size=50):
    """Generate 500 memories for a single life phase via Gemini, in batches of 50."""
    phase_id = phase["id"]
    label = phase["label"]
    yr_start, yr_end = phase["years"]
    context = phase["prompt_context"]
    output_file = DATASET_DIR / f"corpus-bio-{phase_id}.jsonl"

    print(f"\n{'='*70}")
    print(f"  BIOGRAPHICAL PHASE: {label}")
    print(f"  Output: {output_file}")
    print(f"{'='*70}")

    all_records = []
    num_batches = 10  # 10 batches  50 = 500

    for batch_idx in range(num_batches):
        batch_num = batch_idx + 1
        year_focus_start = yr_start + (yr_end - yr_start) * batch_idx // num_batches
        year_focus_end = yr_start + (yr_end - yr_start) * (batch_idx + 1) // num_batches

        prompt = f"""You are generating authentic autobiographical memories for a person named Mike Thompson.
These are memories from the perspective of an adult looking back on this period of his life,
as if he were telling his AI companion Jarvis about them.

LIFE PHASE: {label}
YEAR FOCUS FOR THIS BATCH: {year_focus_start} to {year_focus_end}

DETAILED CONTEXT:
{context}

CRITICAL RULES:
1. Generate exactly {batch_size} distinct memories as a JSON array.
2. Each memory is a natural conversational exchange  Mike telling Jarvis about a memory,
   and Jarvis responding. These should feel like real conversations, not database entries.
3. VARY the emotional tone: some memories are joyful, some embarrassing, some mundane,
   some bittersweet, some traumatic, some funny, some boring.
4. VARY the length: some are 8 words ("Remember that dog we had? Bruno?"), some are
   80 words (a full story about a specific day).
5. Include SPECIFIC details that make memories feel real: brand names, exact dates,
   weather, what someone was wearing, the song playing, the smell of something.
6. Some memories should be FRAGMENTARY  "I think it was a Tuesday? Or maybe Wednesday.
   We were at Grandpa Arthur's and he was telling that story about the bridge in France..."
7. Some should reference OTHER memories: "This was right after Emily broke her arm, remember?"
8. Jarvis's responses should vary: sometimes empathetic, sometimes factual, sometimes
   asking a follow-up question, sometimes brief ("I remember that well.").
9. DO NOT use the same opening pattern for multiple memories. No "I remember when..." for
   every single one.
10. Include at least 5 memories that are SENSORY (sounds, smells, textures, tastes) rather
    than narrative.

Return JSON array:
[
  {{
    "year": 1994,
    "month": 7,
    "day": 15,
    "hour": 14,
    "userText": "...",
    "jarvisText": "...",
    "synapticTags": ["childhood", "summer", "swimming"],
    "valence": 75,
    "importance": 3.5,
    "arousal": 90
  }}
]
"""
        print(f"  Batch {batch_num}/{num_batches} (years {year_focus_start}-{year_focus_end})...", end=" ", flush=True)
        result = call_gemini(prompt)

        if not result:
            print(f"EMPTY  skipping batch {batch_num}")
            continue

        batch_records = []
        for item in result:
            try:
                yr = max(yr_start, min(yr_end, int(item.get("year", yr_start))))
                mo = max(1, min(12, int(item.get("month", 6))))
                dy = max(1, min(28, int(item.get("day", 15))))
                hr = max(0, min(23, int(item.get("hour", 14))))
                dt = datetime.datetime(yr, mo, dy, hr, 0)

                rec_id = f"bio-{phase_id}-{len(all_records)+len(batch_records)+1:04d}"
                sess_id = f"session-bio-{dt.strftime('%Y%m%d')}-{random.randint(1,99):02d}"
                u_text = item.get("userText", "")
                j_text = item.get("jarvisText", "")
                tags = item.get("synapticTags", [phase_id, "biographical"])

                if not u_text:
                    continue

                # User turn
                batch_records.append({
                    "id": rec_id,
                    "text": u_text,
                    "synapticTags": tags,
                    "valence": int(item.get("valence", 30)),
                    "importance": float(item.get("importance", 3.0)),
                    "arousal": int(item.get("arousal", 60)),
                    "sessionId": sess_id,
                    "timestampMs": to_epoch_ms(dt),
                    "entityMentions": detect_entities(u_text),
                    "memoryType": "EPISODIC",
                    "agentRecallCount": 0,
                })

                # Jarvis turn
                if j_text:
                    batch_records.append({
                        "id": f"{rec_id}-j",
                        "text": j_text,
                        "synapticTags": tags,
                        "valence": int(item.get("valence", 30) * 0.5),
                        "importance": round(float(item.get("importance", 3.0)) * 0.85, 2),
                        "arousal": int(item.get("arousal", 60) * 0.4),
                        "sessionId": sess_id,
                        "timestampMs": to_epoch_ms(dt + datetime.timedelta(seconds=30)),
                        "entityMentions": detect_entities(j_text),
                        "memoryType": "SEMANTIC",
                        "agentRecallCount": 0,
                    })
            except Exception as e:
                print(f"  [skip record: {e}]", end="")
                continue

        all_records.extend(batch_records)
        print(f"{len(batch_records)} records")
        time.sleep(0.5)  # Gentle rate limiting

    # Write output
    with open(output_file, "w", encoding="utf-8") as f:
        for r in all_records:
            f.write(json.dumps(r) + "\n")

    print(f"   Phase '{label}' complete: {len(all_records)} records  {output_file.name}")
    return len(all_records)


# ===================================================================
# PART 2: DAILY EPOCH (2024-2026)  Gemini per day, weekly batches
# ===================================================================

# Quarterly Life Arcs  unique narrative context per quarter
QUARTERLY_ARCS = {
    (2024, 1): {
        "career": "Under intense pressure to ship CareConnect v1 MVP by March. Greg Holloway (VP Engineering) pushing back on in-app messaging scope. Anika Patel (junior PM Mike is mentoring) doing user research showing 73% of clinical beta testers want messaging. Daily standups feeling tense.",
        "family": "Ethan (age 7) in 2nd grade, learning multiplication tables. Lily (18 months) teething badly, waking up at 2-3 AM screaming. Sarah exhausted from nighttime duty. Cooper chewed through a pair of Sarah's favorite shoes.",
        "health": "Training for Cowtown Half Marathon in Fort Worth (Feb 24). Running 4x/week, sometimes at 5:30 AM before Lily wakes. Cold January mornings on the trail.",
        "home": "Still settling into the Frisco house (moved 18 months ago). Guest bedroom still has unpacked boxes. Garage workshop half-organized  workbench built but wall storage not done yet.",
        "eldercare": "Tom's knee replacement recovery going well. PT 3x/week at Northwestern in Chicago. Linda taking him to appointments. Tom getting restless being unable to walk properly.",
        "weather": "Cold and gray North Texas winter. Occasional ice storms. Fireplace getting heavy use.",
    },
    (2024, 4): {
        "career": "CareConnect v1 launched successfully at Baylor Scott & White pilot. Post-launch bug fixes and v1.1 roadmap planning. Anika getting promoted to Senior PM  Mike proud. Greg Holloway grudgingly admitting messaging was the right call.",
        "family": "Ethan's spring soccer season at Frisco FC starting. Practices Tue/Thu at Warren Sports Complex. Lily (22 months) walking confidently, getting into EVERYTHING. Cooper discovered squirrels in the backyard.",
        "health": "Completed Cowtown Half Marathon in 1:42! Switched to trail running at Arbor Hills. North Texas allergies (cedar, ragweed) are brutal.",
        "home": "Started building the walnut dining table  first major project with Robert's Lie-Nielsen planes. Sarah redesigning home office for DesignSystemsPro video courses.",
        "eldercare": "Planning summer trip to Naperville. Tom walking without cane for the first time! Linda planning a small celebration dinner.",
        "weather": "Beautiful Texas spring, but severe thunderstorm season starting. Tornado watches some evenings.",
    },
    (2024, 7): {
        "career": "CareConnect v1.1 in development. FHIR webhook integration debate with platform team. Exploring Clinical AI triage as next product bet. Summer intern joining  Mike's first time managing an intern.",
        "family": "Summer break chaos  Ethan home all day, Lily in half-day daycare. Family road trip to Galveston beach planned for July 4th. Ethan starting piano lessons with Mrs. Yamamoto. Cooper scared of fireworks.",
        "health": "Too hot for midday runs. Morning 6 AM runs only. Swimming at Frisco Aquatic Center on weekends. Mike tweaked his ankle on a trail root.",
        "home": "Walnut dining table legs joined. Working on the tabletop glue-up. Sarah painting the nursery accent wall dusty rose.",
        "eldercare": "Tom and Linda visiting Frisco for two weeks in July. Tom teaching Ethan about WWII history using Arthur's Elgin watch. Patricia in Austin adjusting to widowhood.",
        "weather": "Brutal Texas summer heat. 105F days. Water restrictions in effect. Lawn going brown.",
    },
    (2024, 10): {
        "career": "Clinical AI triage prototype getting executive buy-in. Promoted to Principal PM effective January 2025. Year-end planning and OKR setting. Performance reviews for Anika.",
        "family": "Ethan's fall soccer season and first piano recital (Clementi Sonatina). Lily (2.5) starting at Little Sprouts Pre-K, having separation anxiety first week. Halloween costume planning  Ethan wants to be an astronaut, Lily wants to be Cooper.",
        "health": "Running weather is back! Perfect 60F mornings. Training for a Thanksgiving turkey trot 10K.",
        "home": "Walnut dining table DONE. First family dinner at the new table  emotional moment thinking about Robert. Starting end-grain cutting board as Christmas gifts.",
        "eldercare": "Tom's knee recovery complete. Discussing Thanksgiving plans  Tom and Linda flying to Frisco. Emily and Mark possibly driving from Denver with Maya.",
        "weather": "Beautiful Texas fall. State Fair of Texas in Dallas. Crisp mornings and warm afternoons.",
    },
    (2025, 1): {
        "career": "Now Principal PM. Officially leading Clinical AI triage platform. Hiring two PMs for the CareConnect team. Greg Holloway leaving Vertex (going to a startup). New VP Engineering: Priya Venkatesh  much better to work with.",
        "family": "Ethan (age 8) in 3rd grade. Piano progressing to Bach Two-Part Inventions. Lily (2) fully at Little Sprouts, making friends with a girl named Chloe. Cooper got a clean bill of health at annual vet checkup.",
        "health": "New Year's resolution: add strength training to running. Bought a kettlebell set for the garage. Trying to fix chronic lower back stiffness.",
        "home": "Organizing the garage workshop properly  building a French cleat wall for tools. Sarah's DesignSystemsPro course hit 1,000 students.",
        "eldercare": "Tom slipped on ice in Naperville and bruised his hip. Linda worried. Emily checking in from Denver. Discussion about whether Tom and Linda should consider a warmer climate.",
        "weather": "Mild Texas winter. One ice storm in late January that shut down schools for two days.",
    },
    (2025, 4): {
        "career": "Clinical AI triage in alpha testing at two hospital partners. First real patient routing decisions. Legal and compliance review of AI medical decisions. Late nights and weekend work.",
        "family": "Ethan's spring soccer season. He scored his first hat trick! Sarah submitted her course for a design education award. Lily obsessed with painting  fingers, paper, walls, Cooper.",
        "health": "Running strong  sub-8:00 pace consistently. Entered the Frisco Freedom 5K for July 4th. Kettlebell routine helping back pain.",
        "home": "Building floating white oak shelves for Sarah's studio. Experimenting with Japanese joinery (no screws/nails).",
        "eldercare": "Patricia in Austin having cataract surgery. Daniel flew in from Seattle to help her. Mike and Sarah drove down for the weekend.",
        "weather": "Severe thunderstorm season. One tornado warning had the family in the hall closet with Cooper at 11 PM.",
    },
    (2025, 7): {
        "career": "Clinical AI triage beta launch at 5 hospital partners. Media attention  local healthcare publication interview. Vertex Health Q2 earnings call mentioned the product. Mike presenting at a Houston HealthTech conference.",
        "family": "Summer road trip to Colorado  Emily's family, camping near Boulder. Ethan and Maya (Emily's daughter) building forts. Lily's first time seeing mountains. Cooper got carsick in the SUV.",
        "health": "Altitude running in Colorado was humbling. Back to Texas heat runs at dawn. Considering a Peloton bike for indoor cross-training.",
        "home": "Japanese joinery shelves installed  Sarah loves them. Started restoring a mid-century Danish teak record console found at a Plano estate sale.",
        "eldercare": "Tom's 70th birthday party planned for September in Naperville. All siblings coordinating. Emily suggesting a family photo session.",
        "weather": "Record-breaking Texas heat. 108F one day. Swimming pool at the community center packed.",
    },
    (2025, 10): {
        "career": "Clinical AI triage expanded to 8 hospital partners. Zero critical misclassifications across 15,000 patient encounters. Planning 2026 rollout to 14-hospital network. Year-end board presentation.",
        "family": "Ethan (age 9) fall soccer and piano recital (Bach Invention No. 8). Lily (3.5) in Pre-K dance class. Halloween: Ethan was a robot, Lily was a butterfly. Family Thanksgiving in Naperville  all Thompson and Miller families together.",
        "health": "Ran a personal best 10K at 46:12. Feeling strongest in years. Sarah joined him for weekend jogs.",
        "home": "Record console restoration complete  looks stunning in the living room. Planning a built-in bookcase for the study.",
        "eldercare": "Tom's 70th birthday celebration in Naperville was wonderful. He got emotional talking about Arthur. Linda pulled Mike aside to discuss long-term care planning.",
        "weather": "Perfect fall weather. Family apple picking at a farm near McKinney.",
    },
    (2026, 1): {
        "career": "14-hospital network rollout begins. Massive coordination effort. Hired a dedicated Clinical AI ops team. Vertex Health IPO rumors circulating. Mike's equity vesting schedule becoming very relevant.",
        "family": "Ethan (age 9) in 4th grade, becoming more independent. Lily (3) potty training  inconsistent progress. Cooper is 4 years old, mellowing out but still steals socks.",
        "health": "Signed up for the Dallas Marathon in December 2026  first full marathon attempt since Chicago in 2014. Base building phase. Ordered new running shoes (Hoka Mach 6).",
        "home": "Study bookcase project started. Using cherry wood for the first time. Sarah wants built-in desk integration.",
        "eldercare": "Tom and Linda seriously discussing selling the Naperville house and moving to a 55+ community near Frisco. Emotional topic  that's the house Mike grew up in.",
        "weather": "Unusually warm January. Some 70F days. Climate change conversations at family dinner.",
    },
    (2026, 4): {
        "career": "Rollout hitting stride  10 of 14 hospitals live. One hospital (Memorial Hermann in Houston) had a complex integration issue that consumed two weeks. Patent approved for clinical triage routing algorithm!",
        "family": "Ethan joined the school robotics club. Building a LEGO Mindstorms robot for a regional competition. Lily (4) doing gymnastics at a Frisco gym. Sarah's course hit 2,000 students  celebrating with a nice dinner at Knife Dallas.",
        "health": "Marathon training getting serious. Long runs on Saturday mornings (14-16 miles). Knee feeling a twinge  icing after runs.",
        "home": "Cherry bookcase with integrated desk finished. Sarah designed custom LED strip lighting for it. Next project: refinishing the front door (sun-damaged).",
        "eldercare": "Tom and Linda put the Naperville house on the market. Mike feels a pang of loss but knows it's the right move. Emily drove up to help them pack.",
        "weather": "Tornado season again. One close call  funnel cloud spotted 3 miles from the house.",
    },
    (2026, 7): {
        "career": "All 14 hospitals live on Clinical AI triage! 98.4% routing accuracy across 42,000 patient encounters. Vertex Health board impressed. Mike invited to speak at HIMSS 2027.",
        "family": "Summer vacation to the Oregon coast  Cannon Beach. Ethan (10) boogie boarding. Lily (4) terrified of the ocean initially, then loved tide pools. Cooper chased seagulls on the beach. Daniel joined from Seattle for part of the trip.",
        "health": "Marathon training through summer heat is brutal. Two 20-mile long runs done. Lost 8 pounds. Eating more protein  Sarah making chicken and quinoa bowls.",
        "home": "Front door refinished with marine-grade spar varnish. Looks like new. Starting to plan Ethan's bedroom renovation  he wants a loft bed with a reading nook underneath.",
        "eldercare": "Naperville house sold. Tom and Linda moved into Heritage Ranch 55+ community in Frisco! They're 15 minutes away now. Tom joined a local veterans' group.",
        "weather": "Another scorching Texas summer. Installed a misting system on the back patio.",
    },
    (2026, 10): {
        "career": "Vertex Health IPO filed. Mike's equity stake becoming real. Clinical AI triage platform getting national press coverage. Recruiting for 2027 expansion team.",
        "family": "Ethan's robotics team won regionals! Advancing to state competition in Austin. Lily (4.5) can write her name and read simple books. Cooper is the neighborhood celebrity  all the kids on the street know him. Family Thanksgiving with Tom and Linda just 15 minutes away for the first time ever.",
        "health": "Dallas Marathon in December! Taper phase. Mike nervous but ready. Goal: sub-3:45. Sarah bought him a 'Marathon Dad' shirt.",
        "home": "Ethan's loft bed with reading nook built. Used maple and walnut  Mike's most complex woodworking project yet. Lily already jealous and wanting one too.",
        "eldercare": "Tom thriving at Heritage Ranch. Made friends, attending history lectures at the community center. Linda started a book club. Patricia visited from Austin for Thanksgiving.",
        "weather": "Beautiful Texas fall. Cool enough for evening walks with Cooper. First frost of the season.",
    },
}

# 100+ Surprise Events
SURPRISE_EVENTS = [
    # Home emergencies
    "Cooper ate an entire bag of chocolate chips off the kitchen counter. Frantic call to Frisco emergency vet at 10 PM. Vet said to monitor but he'll probably be okay.",
    "Massive hailstorm hit the neighborhood  golf-ball-sized. Three windows cracked. Roof damage. Insurance adjuster appointment scheduled.",
    "Garbage disposal jammed with a bottle cap. Mike spent 45 minutes under the kitchen sink with an Allen wrench and a flashlight. Hands covered in gunk.",
    "Power outage during ice storm lasted 14 hours. Family huddled in sleeping bags in the living room. Played board games by candlelight. Cooper wouldn't stop pacing.",
    "Dishwasher leaked and flooded the kitchen floor at 11 PM. Towels everywhere. Had to call a 24-hour plumber.",
    "Smoke detector batteries all died at 3 AM. Piercing beeping woke up the entire house. Lily screamed bloody murder.",
    "AC unit died on a 104F day. Repair tech couldn't come until tomorrow. Family went to a movie theater to cool off.",
    "Skunk sprayed Cooper in the backyard at dusk. Tomato juice bath in the garage. House smelled for days.",
    "Found a scorpion in the bathroom. Sarah screamed. Mike trapped it under a glass. Pest control coming Monday.",
    "Water heater started leaking in the garage. Had to shut off the water main and call an emergency plumber.",
    # Kid moments
    "Ethan got stung by a wasp at soccer practice. Swelled up pretty bad. Coach had to dig out the stinger with tweezers.",
    "Lily said her first full sentence: 'Cooper eat my cookie!' Everyone died laughing.",
    "Ethan failed his math test. Mike did flashcards with him after dinner for an hour. Ethan frustrated, then slowly got it.",
    "Lily had a full meltdown at Target because Mike wouldn't buy the purple unicorn. Laid on the floor screaming. Every parent in the store gave Mike that knowing look.",
    "Ethan lost his first baby tooth at dinner. Put it under his pillow. Mike almost forgot to do the tooth fairy thing.",
    "Lily drew a family portrait where Cooper is bigger than the house. Mike framed it.",
    "Ethan asked where babies come from during a car ride. Mike and Sarah exchanged panicked looks. Sarah handled it gracefully.",
    "School nurse called  Ethan has a 101F fever. Mike left work early to pick him up. Strep throat confirmed.",
    "Lily refused to wear anything except her Elsa dress for 6 straight days. Preschool teachers gave up trying.",
    "Ethan read his first chapter book cover to cover (Magic Tree House). So proud he carried it to school to show friends.",
    # Work crises
    "Production outage at 2 AM  hospital webhook pipeline down. 47-minute mean time to recovery. Post-mortem meeting at 8 AM. Mike running on 3 hours sleep.",
    "Greg Holloway sent a passive-aggressive Slack message about the messaging module timeline. Mike vented to Sarah about corporate politics.",
    "Got the patent approval email for the clinical triage routing algorithm! Forwarded it to the whole team. Vertex Health legal sending a plaque.",
    "Anika came to Mike's office in tears  she's dealing with impostor syndrome after a tough stakeholder meeting. Mike spent an hour coaching her.",
    "Laptop crashed during a live demo to hospital CIOs. Blue screen of death. Mike improvised from memory for 10 minutes while IT fixed it.",
    "Competitor launched a similar product. Vertex Health executive panic. Emergency strategy session.",
    "Mike's intern wrote a SQL query that accidentally updated 3,000 patient records in staging. Caught before production.",
    "Annual performance review  Mike got 'exceeds expectations' and a 12% raise. Celebrated with Sarah at a sushi restaurant.",
    # Woodworking
    "Miscalculated a mortise depth on the walnut table leg by 3mm. Had to glue in a Dutchman patch. Frustrating but salvageable.",
    "Dropped the Lie-Nielsen No. 4 on the concrete garage floor. Chipped the cutting edge. Spent an hour at the sharpening station re-honing.",
    "Finally got glass-smooth finish on cherry without sandpaper  blade tuned to take 0.001\" shavings. Robert would be proud.",
    "Ordered wrong lumber dimensions online. Had to wait 2 weeks for the replacement. Project stalled.",
    "Found a stunning piece of figured maple at a local lumber yard. Couldn't resist buying it even though there's no project planned.",
    "Teaching Ethan to use the hand saw safely. He cut a wobbly straight line and beamed with pride.",
    # Social / extended family
    "Daniel's flight got diverted to DFW due to weather. Surprise dinner at Pecan Lodge BBQ in Deep Ellum.",
    "Emily called crying  Maya fell off the monkey bars and broke her arm. Mark rushing her to Denver Children's Hospital.",
    "Dave Nguyen in town for a conference. Beers and reminiscing about UIUC at a craft brewery in Bishop Arts.",
    "Patricia fell in her Austin kitchen and bruised her tailbone. Sarah worried. Discussed whether Patricia should move closer.",
    "Tom and Mike went to a Texas Rangers game. Tom caught a foul ball. Best day he's had in months.",
    "Sarah's DesignSystemsPro course got a scathing 1-star review. She was upset all evening. Mike listened.",
    "Neighborhood block party. Met new neighbors  the Garcias have a kid Ethan's age named Marco. Instant friends.",
    "Mike's high school friend Danny Kowalski reached out on Facebook. Hadn't talked in 12 years. Caught up over a long phone call.",
    # Mundane but real
    "Flat tire on the way to Vertex Health. Changed it in the Plano office parking lot in dress clothes. Shirt ruined.",
    "Sarah and Mike had a tense argument about the kitchen backsplash tile. She wants subway, he wants herringbone. Agreed on herringbone the next morning.",
    "Spent 3 hours on hold with First Texas National Bank about mortgage refinance paperwork. Finally talked to someone who couldn't help anyway.",
    "Car registration renewal at the Collin County office. 90-minute wait. Read an entire chapter of a book.",
    "Mike locked himself out of the house while taking out the trash. Had to climb through the bathroom window. Cooper watched from inside, confused.",
    "Grocery run at Central Market turned into a $287 bill. Sarah: 'How?' Mike: 'There was cheese.'",
    "Jury duty summons arrived. Mike spent a full day at the Collin County courthouse. Not selected.",
    "Mike tried to fix the dripping kitchen faucet himself. Made it worse. Called a plumber.",
    "Lost his AirPods somewhere in the house. Found them in Cooper's bed three days later.",
    "Sunday afternoon nap on the couch that turned into 3 hours. Woke up groggy with Cooper on his legs.",
    # Hobbies and interests
    "Tried smoking a pork shoulder for 12 hours. Oversalted the rub. Family was polite about it.",
    "Watched a documentary about Japanese woodworking. Inspired to try kumiko lattice work.",
    "Sarah and Mike tried a new Indian restaurant in Frisco. Best butter chicken they've ever had. Went back the next week.",
    "Took Ethan to his first concert  a local kids' music festival at Toyota Stadium.",
    "Mike attempted sourdough bread for the first time. The starter died after 4 days. Started over.",
    "Found an old box of photos from the Naperville house. Spent an hour with Sarah looking through them. Got emotional.",
    "Tried to teach Cooper to fetch a specific toy by name. Cooper fetched the wrong one every time but with maximum enthusiasm.",
    "Binge-watched a woodworking YouTube channel until 1 AM. Sarah found him asleep on the couch with sawdust videos playing.",
]

def get_quarter_key(date):
    """Return (year, quarter_start_month) for a given date."""
    q = ((date.month - 1) // 3) * 3 + 1
    return (date.year, q)

def build_daily_prompt(date, day_num, quarter_arc, surprise_events, continuity_summary):
    """Build a rich, unique per-day prompt for Gemini."""
    dow = date.strftime("%A")
    is_weekend = dow in ("Saturday", "Sunday")

    event_block = ""
    if surprise_events:
        event_block = "TODAY'S SPECIFIC EVENTS (weave these naturally into the conversations):\n"
        for e in surprise_events:
            event_block += f"- {e}\n"
    else:
        event_block = "TODAY: A relatively normal day. No major surprises."

    continuity_block = ""
    if continuity_summary:
        continuity_block = f"""WHAT HAPPENED IN THE LAST FEW DAYS (reference these naturally  don't repeat them word for word, but Mike might follow up on unresolved items or mention things casually):
{continuity_summary}"""

    weekend_note = ""
    if is_weekend:
        weekend_note = """
TODAY IS A WEEKEND. Mike is NOT at work (unless there's an emergency). Weekend days are more:
- Family-focused: park visits, grocery runs, cooking together, Ethan's soccer games
- Hobby-focused: extended woodworking sessions, BBQ smoking, home projects
- Relaxed: sleeping in, lazy breakfast, watching a movie with kids
- Variable: some weekends are packed with activities, some are gloriously empty
Generate 1-3 sessions (not 4). Weekend mornings start later (9-10 AM, not 7:30)."""

    return f"""Generate a full day of natural, realistic conversations between Mike Thompson and his AI companion Jarvis for {dow}, {date.strftime('%B %d, %Y')} (Day {day_num} of the MindSpan dataset).

PERSONA: Mike Thompson, Principal Product Manager at Vertex Health in Frisco, TX.
His AI companion Jarvis has been with him for years and knows everything about his life.

CURRENT LIFE CONTEXT THIS QUARTER:
Career: {quarter_arc.get('career', 'Normal workday.')}
Family: {quarter_arc.get('family', 'Family routine.')}
Health: {quarter_arc.get('health', 'Regular exercise routine.')}
Home: {quarter_arc.get('home', 'Normal home life.')}
Eldercare: {quarter_arc.get('eldercare', 'Family health stable.')}
Weather: {quarter_arc.get('weather', 'Typical Texas weather.')}

{event_block}

{continuity_block}
{weekend_note}

CRITICAL RULES FOR NATURAL, REALISTIC DIALOGUE:
1. DO NOT start any session with "Good morning Jarvis" or any templated greeting. Jump straight into whatever Mike is thinking about, dealing with, or reacting to.
2. VARY Mike's message lengths WILDLY within the same day:
   - Some are 3-8 words: "Yeah, the second one", "Did she text back?", "Hmm not sure about that", "Oh man"
   - Some are 15-30 words: a quick question or comment
   - Some are 50-100 words: a story, a rant, a detailed request
3. Include at least ONE vague/ambiguous reference that only makes sense from prior context (e.g. "did she finish it?", "what was that restaurant again?", "the one from last week").
4. Include at least ONE "by the way" moment where Mike drops a fact while asking about something else (e.g. "Can you check the weather? By the way, Ethan got an A on his science project").
5. Some of Jarvis's responses should be SHORT: "Done.", "I don't have that information yet.", "Checking now."
6. At least one session should have a MULTI-TURN decision arc (3-5 exchanges narrowing down a choice).
7. Include ambient sensory context ONLY 2-3 times across the whole day, not every turn. Use [Audio:], [Visual:], or [Sensor:] tags.
8. Some turns should have NATURAL MISTAKES or corrections: "Wait no, I think it was Thursday not Wednesday", "Actually, scratch that  let's do the other one".
9. Generate 2-5 sessions (NOT always exactly 4). Some days Mike barely talks to Jarvis. Other days it's constant.
10. Each session should have 2-8 dialogue turns (NOT always exactly 2). Vary it.
11. Session times should VARY  not always the same times each day. Sometimes Mike talks to Jarvis at 6:15 AM, sometimes not until 10 AM.
12. Do NOT mention "Cottonwood Creek Trail", "Lie-Nielsen", "CareConnect", "soccer", or "piano" unless it's genuinely relevant to today's events. Mike doesn't do ALL his hobbies EVERY day.

Return a JSON array of session objects:
[
  {{
    "sessionName": "descriptive-name-not-generic",
    "hour": 7,
    "minute": 42,
    "dialogue": [
      {{"speaker": "user", "text": "...", "valence": -20, "importance": 3.5, "arousal": 80, "tags": ["specific", "relevant", "tags"]}},
      {{"speaker": "jarvis", "text": "...", "valence": 5, "importance": 2.0, "arousal": 30, "tags": ["response", "tags"]}}
    ]
  }}
]
"""

def extract_day_summary(day_records):
    """Extract a brief summary of the day's key events for continuity buffer."""
    texts = []
    for r in day_records[:12]:  # Cap at 12 turns to keep prompt size reasonable
        texts.append(r.get("text", "")[:150])

    prompt = f"""Read these conversation excerpts from today and summarize the 3-5 most important things
that happened. Focus on: unresolved items, decisions made, emotional events, specific facts
(names, dates, amounts, places) that Mike might reference tomorrow. Keep it under 200 words.

{chr(10).join(texts)}

Return JSON: {{"summary": "..."}}"""

    result = call_gemini(prompt, temperature=0.3)
    if isinstance(result, dict):
        return result.get("summary", "")
    return ""

def synthesize_daily_batch(start_day, count_days, checkpoint):
    """Generate a batch of days via Gemini with continuity buffer."""
    start_date = datetime.date(2024, 1, 1)
    continuity = load_continuity()
    recent_summaries = continuity.get("recent_days", [])

    for d_idx in range(count_days):
        abs_day = start_day + d_idx
        if abs_day > 1095:
            break
        cur_date = start_date + datetime.timedelta(days=abs_day - 1)
        day_num = abs_day

        if day_num in checkpoint.get("daily_days_done", []):
            print(f"  Day {day_num:04d} ({cur_date}): already done, skipping")
            continue

        # Get quarterly context
        qkey = get_quarter_key(cur_date)
        quarter_arc = QUARTERLY_ARCS.get(qkey, QUARTERLY_ARCS.get((qkey[0], 1), {}))

        # Sample surprise events (70% chance of 0, 25% chance of 1, 5% chance of 2)
        roll = random.random()
        num_surprises = 0 if roll < 0.70 else (1 if roll < 0.95 else 2)
        surprise_events = random.sample(SURPRISE_EVENTS, min(num_surprises, len(SURPRISE_EVENTS)))

        # Build continuity summary from recent 3 days
        continuity_summary = "\n".join(recent_summaries[-3:]) if recent_summaries else ""

        # Build prompt and call Gemini
        prompt = build_daily_prompt(cur_date, day_num, quarter_arc, surprise_events, continuity_summary)

        print(f"  Day {day_num:04d} ({cur_date}, {cur_date.strftime('%A')})...", end=" ", flush=True)
        sessions_data = call_gemini(prompt)

        if not sessions_data:
            print("EMPTY  skipping")
            continue

        daily_records = []
        turn_counter = 1

        for sess in sessions_data:
            if not isinstance(sess, dict):
                continue
            s_name = sess.get("sessionName", f"session-{turn_counter}")
            s_hour = max(0, min(23, int(sess.get("hour", 12))))
            s_min = max(0, min(59, int(sess.get("minute", 0))))
            s_dt = datetime.datetime.combine(cur_date, datetime.time(s_hour, s_min))
            s_id = f"session-{cur_date.strftime('%Y-%m-%d')}-{s_name}"

            for t in sess.get("dialogue", []):
                if not isinstance(t, dict):
                    continue
                txt = t.get("text", "")
                if not txt:
                    continue
                speaker = t.get("speaker", "user")
                m_id = f"mem-d{day_num:04d}-{turn_counter:03d}"
                turn_counter += 1

                daily_records.append({
                    "id": m_id,
                    "text": txt,
                    "synapticTags": t.get("tags", ["daily"]),
                    "valence": int(t.get("valence", 0)),
                    "importance": float(t.get("importance", 1.5)),
                    "arousal": int(t.get("arousal", 50)),
                    "sessionId": s_id,
                    "timestampMs": to_epoch_ms(s_dt + datetime.timedelta(seconds=turn_counter * 30)),
                    "entityMentions": detect_entities(txt),
                    "memoryType": "EPISODIC" if speaker == "user" else "SEMANTIC",
                    "agentRecallCount": 0,
                })

        # Write daily file
        day_file = DAILY_DIR / f"corpus-day-{day_num:04d}.jsonl"
        with open(day_file, "w", encoding="utf-8") as f:
            for r in daily_records:
                f.write(json.dumps(r) + "\n")

        print(f"{len(daily_records)} turns across {len(sessions_data)} sessions")

        # Extract day summary for continuity buffer
        if daily_records:
            summary = extract_day_summary(daily_records)
            if summary:
                recent_summaries.append(f"[{cur_date}] {summary}")
                # Keep only last 5 days
                recent_summaries = recent_summaries[-5:]

        # Update checkpoint
        checkpoint.setdefault("daily_days_done", []).append(day_num)
        save_checkpoint(checkpoint)
        save_continuity({"recent_days": recent_summaries})

        time.sleep(0.3)  # Gentle rate limiting

    return checkpoint

# ===================================================================
# PART 3: REBUILD MASTER CORPUS
# ===================================================================
def rebuild_master_corpus():
    """Concatenate all biographical + daily files into corpus.jsonl."""
    print("\n" + "=" * 70)
    print("  REBUILDING MASTER CORPUS")
    print("=" * 70)

    all_records = []

    # Load biographical files
    for bio_file in sorted(DATASET_DIR.glob("corpus-bio-*.jsonl")):
        with open(bio_file, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    all_records.append(json.loads(line))
        print(f"  Loaded {bio_file.name}")

    # Load daily files
    for day_file in sorted(DAILY_DIR.glob("corpus-day-*.jsonl")):
        with open(day_file, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    all_records.append(json.loads(line))

    # Sort by timestamp
    all_records.sort(key=lambda r: r.get("timestampMs", 0))

    # Write master corpus
    master_file = DATASET_DIR / "corpus.jsonl"
    with open(master_file, "w", encoding="utf-8") as f:
        for r in all_records:
            f.write(json.dumps(r) + "\n")

    print(f"\n   Master corpus rebuilt: {len(all_records)} total records  corpus.jsonl")
    return len(all_records)


# ===================================================================
# MAIN ENTRY POINT
# ===================================================================
def main():
    import argparse
    parser = argparse.ArgumentParser(description="MindSpan v2 Gemini Synthesizer")
    parser.add_argument("--phase", choices=["bio", "daily", "rebuild", "all"], default="all",
                        help="Which phase to run")
    parser.add_argument("--bio-phase", type=str, default=None,
                        help="Specific biographical phase ID to generate (e.g. 'early_childhood')")
    parser.add_argument("--start-day", type=int, default=1,
                        help="Start day for daily generation (1-1095)")
    parser.add_argument("--num-days", type=int, default=BATCH_SIZE,
                        help="Number of days to generate in this batch")
    args = parser.parse_args()

    checkpoint = load_checkpoint()

    print("=" * 70)
    print("  MINDSPAN v2 -- GEMINI-3.1-FLASH-LITE SYNTHESIZER")
    print(f"  Model: {MODEL} | Temperature: {TEMPERATURE}")
    print(f"  Phase: {args.phase}")
    print("=" * 70)

    if args.phase in ("bio", "all"):
        for phase in LIFE_PHASES:
            if args.bio_phase and phase["id"] != args.bio_phase:
                continue
            if phase["id"] in checkpoint.get("bio_phases_done", []):
                print(f"\n  Phase '{phase['label']}' already done, skipping.")
                continue

            count = generate_biographical_phase(phase)
            if count > 0:
                checkpoint.setdefault("bio_phases_done", []).append(phase["id"])
                save_checkpoint(checkpoint)

    if args.phase in ("daily", "all"):
        print(f"\n  Generating days {args.start_day} to {args.start_day + args.num_days - 1}...")
        synthesize_daily_batch(args.start_day, args.num_days, checkpoint)

    if args.phase in ("rebuild", "all"):
        rebuild_master_corpus()

    print("\n" + "=" * 70)
    print("   MINDSPAN v2 SYNTHESIS COMPLETE")
    print("=" * 70)


if __name__ == "__main__":
    main()
